version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    resource_class: kawaiimoekid/pi-test
    steps:
      - checkout
      - run: 
          name: Build
          command: dotnet build
