version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    resource_class: kawaiimoekid/pi-test
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run: 
          name: Build
          command: dotnet build
      - run:
          name: Run
          command: dotnet run